### ISSUE TITLE
Add contributing information

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/pspdev.github.io#20]
We are missing a how to contribute page, which I think could be useful.

**Comment by diamant3** [comment]
Hello wouter, I already add that in my PR #18, here https://github.com/diamant3/pspdev.github.io/blob/use-jtd/README.md, what do you think, is this sufficient for those who want to contribute?

**Comment by sharkwouter** [comment]
I was more thinking an additional page on the website which lets the viewer know how to contribute to PSPDEV in general. Which is not in the scope of that specific PR. Cool that you added some info on how to contribute to this project, though.

**Comment by diamant3** [comment]
That would be great wouter! and it's much better if the one who will write was more knowledge about the whole PSP development.

**Comment by sharkwouter** [comment]
I can do it, but I'll do it after the new layout has been merged.
