### ISSUE TITLE
We have no license on this repo

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/pspdev.github.io#52]
It seems we forgot at add a license to this repo. Would it be okay if I change it to be the [unlicense](https://unlicense.org/)?

Please comment if you approve:

- [x] @sharkwouter 
- [x] @diamant3 
- [x] @bucanero 
- [x] @wally4000 
- [x] @TheMrIron2 
- [x] @davidgfnet

**Comment by wally4000** [comment]
Sounds good to me

**Comment by diamant3** [comment]
yes, totally okay to me 👍🏼

**Comment by bucanero** [comment]
All good 👍🏻

**Comment by TheMrIron2** [comment]
All good!

**Comment by davidgfnet** [comment]
LGTM!

**Comment by sharkwouter** [comment]
Thanks everyone, I have created a merge request with the unlicense license: https://github.com/pspdev/pspdev.github.io/pull/57

**Comment by sharkwouter** [comment]
The unlicense qas added to therepo now.
