### ISSUE TITLE
Detailed descriptions of reserved keyword of PSP specific build options

### ISSUE THREAD

**Issue by diamant3** [pspdev/pspdev.github.io#53]
Detailed description of reserved keyword of the build options(`Makefile/CMakelists.txt`) used to make a homebrews.

For those who want to make a PR for this, feel free to comment if you want to. I think this is the list on which those build options reside:

- https://github.com/pspdev/pspsdk/blob/master/src/base/CreatePBP.cmake
- https://github.com/pspdev/pspsdk/blob/master/src/base/build.mak
- https://github.com/pspdev/pspsdk/blob/master/src/base/build_prx.mak

**Comment by sharkwouter** [comment]
I don't know if that does not go a bit too in depth. We already have some explanation of options for CreatePBP.cmake in the tips and tricks and the debugging section.

I think linking to the samples in PSPSDK and the PSPSDK documentation website with a short description at the bottom of the examples we already have could be really useful, though.

What do you think? Where would you put it? What do you think should there specifically?

**Comment by diamant3** [comment]
You are right. This would be a bit too deep to explain, and also the problem is the place where it should be. I'll close this one. Thanks for pointing it out.
